<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="MFAC.MFAC" tests="32" failures="18" timestamp="04 Jan 2019 19:43:54 GMT" time="724.342" errors="0">
  <testcase name="VerifyPinValid" time="27.963" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinVelocity" time="2.552" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;66db0677-6947-4613-bd2a-6fef7e185742&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"66db0677-6947-4613-bd2a-6fef7e185742","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinVelocity(MFAC.java:202)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyPinVelocity -->
  <testcase name="IssuePin" time="10.088" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &quot;pinOTP&quot; and a string containing &quot;pinExpirationDate&quot;)
     but: a string containing &quot;pinOTP&quot; was &quot;{&quot;transactionId&quot;:&quot;6c69b9b2-f247-41e0-9f73-10b9f845feec&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "pinOTP" and a string containing "pinExpirationDate")
     but: a string containing "pinOTP" was "{"transactionId":"6c69b9b2-f247-41e0-9f73-10b9f845feec","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.IssuePin(MFAC.java:147)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePin -->
  <testcase name="VerifyPinVelocity" time="34.516" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinNoLongerValid" time="34.798" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinVelocity" time="32.692" classname="MFAC.MFAC"/>
  <testcase name="IssuePin" time="12.678" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &quot;pinOTP&quot; and a string containing &quot;pinExpirationDate&quot;)
     but: a string containing &quot;pinOTP&quot; was &quot;{&quot;transactionId&quot;:&quot;589d3ba9-5730-4772-8571-ce694011137f&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "pinOTP" and a string containing "pinExpirationDate")
     but: a string containing "pinOTP" was "{"transactionId":"589d3ba9-5730-4772-8571-ce694011137f","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.IssuePin(MFAC.java:147)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePin -->
  <testcase name="VerifyPinValid" time="27.909" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinNoLongerValid" time="17.737" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinOTP&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;786d47e3-646a-4e89-9a38-02352dc1aeeb&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinOTP"
     but: was "{"transactionId":"786d47e3-646a-4e89-9a38-02352dc1aeeb","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinNoLongerValid(MFAC.java:229)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyPinNoLongerValid -->
  <testcase name="IssuePin" time="13.958" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinVelocity" time="31.266" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinVelocity" time="33.380" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinNoLongerValid" time="11.588" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinOTP&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;f6ee3490-5518-4728-beea-225a91b07660&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinOTP"
     but: was "{"transactionId":"f6ee3490-5518-4728-beea-225a91b07660","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinNoLongerValid(MFAC.java:229)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyPinNoLongerValid -->
  <testcase name="AddressVelocity" time="34.936" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;ALLOW&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;5a19df54-d08b-4117-87bd-a44d4476fbd9&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;DENY&quot;,&quot;message&quot;:&quot;Unfortunately, too many failed attempts for registration have occurred. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "ALLOW"
     but: was "{"transactionId":"5a19df54-d08b-4117-87bd-a44d4476fbd9","errors":[{"code":"DENY","message":"Unfortunately, too many failed attempts for registration have occurred. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.AddressVelocity(MFAC.java:128)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AddressVelocity -->
  <testcase name="VerifyPinValid" time="19.465" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;a567db67-c812-4abc-add8-5aae177c9cb4&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"a567db67-c812-4abc-add8-5aae177c9cb4","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinValid(MFAC.java:184)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyPinValid -->
  <testcase name="VerifyPinNoLongerValid" time="35.587" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinVelocity" time="6.138" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;87937ed3-9969-4a99-873c-bf68109f36a2&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"87937ed3-9969-4a99-873c-bf68109f36a2","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinVelocity(MFAC.java:202)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyPinVelocity -->
  <testcase name="VerifyPinValid" time="21.998" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;30d56f57-e408-4956-b31c-08dcac7b3006&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"30d56f57-e408-4956-b31c-08dcac7b3006","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinValid(MFAC.java:184)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyPinValid -->
  <testcase name="IssuePinVelocity" time="34.371" classname="MFAC.MFAC"/>
  <testcase name="AddressVelocity" time="34.642" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;ALLOW&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;6e02498e-e70f-45f5-a5bf-a5b3f30d634b&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;DENY&quot;,&quot;message&quot;:&quot;Unfortunately, too many failed attempts for registration have occurred. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "ALLOW"
     but: was "{"transactionId":"6e02498e-e70f-45f5-a5bf-a5b3f30d634b","errors":[{"code":"DENY","message":"Unfortunately, too many failed attempts for registration have occurred. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.AddressVelocity(MFAC.java:128)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AddressVelocity -->
  <testcase name="IssuePinVelocity" time="15.560" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &quot;pinOTP&quot; and a string containing &quot;pinExpirationDate&quot;)
     but: a string containing &quot;pinOTP&quot; was &quot;{&quot;transactionId&quot;:&quot;a8f9f8c7-3a9c-4cbb-b9ed-bd61df20e9e6&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "pinOTP" and a string containing "pinExpirationDate")
     but: a string containing "pinOTP" was "{"transactionId":"a8f9f8c7-3a9c-4cbb-b9ed-bd61df20e9e6","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.IssuePinVelocity(MFAC.java:165)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
  <testcase name="IssuePinVelocity" time="26.533" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinVelocity" time="4.904" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;f7e4e7bb-c6bf-44ce-ada7-9e36eb623490&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"f7e4e7bb-c6bf-44ce-ada7-9e36eb623490","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinVelocity(MFAC.java:202)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyPinVelocity -->
  <testcase name="AddressVelocity" time="35.747" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;ALLOW&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;835fc60d-3185-4ad7-a1a2-db8ff9874962&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;DENY&quot;,&quot;message&quot;:&quot;Unfortunately, too many failed attempts for registration have occurred. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "ALLOW"
     but: was "{"transactionId":"835fc60d-3185-4ad7-a1a2-db8ff9874962","errors":[{"code":"DENY","message":"Unfortunately, too many failed attempts for registration have occurred. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.AddressVelocity(MFAC.java:128)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AddressVelocity -->
  <testcase name="AddressVelocity" time="35.347" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;ALLOW&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;193faa29-2535-489a-8fe7-ddd05088900d&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;DENY&quot;,&quot;message&quot;:&quot;Unfortunately, too many failed attempts for registration have occurred. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "ALLOW"
     but: was "{"transactionId":"193faa29-2535-489a-8fe7-ddd05088900d","errors":[{"code":"DENY","message":"Unfortunately, too many failed attempts for registration have occurred. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.AddressVelocity(MFAC.java:128)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- AddressVelocity -->
  <testcase name="VerifyPinVelocity" time="35.180" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinVelocity" time="30.995" classname="MFAC.MFAC"/>
  <testcase name="IssuePin" time="23.885" classname="MFAC.MFAC"/>
  <testcase name="VerifyPinVelocity" time="1.447" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;a8d881ff-b180-45f7-8e08-9a060d967cfc&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"a8d881ff-b180-45f7-8e08-9a060d967cfc","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinVelocity(MFAC.java:202)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyPinVelocity -->
  <testcase name="VerifyPinVelocity" time="3.788" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;e0d446a5-f243-4ce7-847f-110a1a84eb91&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"e0d446a5-f243-4ce7-847f-110a1a84eb91","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinVelocity(MFAC.java:202)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyPinVelocity -->
  <testcase name="VerifyPinVelocity" time="7.725" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;pinExpirationDate&quot;
     but: was &quot;{&quot;transactionId&quot;:&quot;bf38a1a2-9d03-4f18-89d1-c5d07a931868&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pinExpirationDate"
     but: was "{"transactionId":"bf38a1a2-9d03-4f18-89d1-c5d07a931868","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.VerifyPinVelocity(MFAC.java:202)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyPinVelocity -->
  <testcase name="IssuePinVelocity" time="24.969" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &quot;pinOTP&quot; and a string containing &quot;pinExpirationDate&quot;)
     but: a string containing &quot;pinOTP&quot; was &quot;{&quot;transactionId&quot;:&quot;2b62bd12-7701-45ee-9bdb-8b2cd0eecac0&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "pinOTP" and a string containing "pinExpirationDate")
     but: a string containing "pinOTP" was "{"transactionId":"2b62bd12-7701-45ee-9bdb-8b2cd0eecac0","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.IssuePinVelocity(MFAC.java:165)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
</testsuite> <!-- MFAC.MFAC -->
