<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="WTC-5159473-l2" name="MFAC.MFAC" tests="4" failures="4" timestamp="06 Feb 2019 19:33:47 GMT" time="16.353" errors="0">
  <testcase name="IssuePinVelocity" time="5.569" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &quot;5700&quot; and a string containing &quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;)
     but: a string containing &quot;5700&quot; was &quot;{&quot;transactionId&quot;:&quot;0ea540f0-30d8-4bcf-be7c-f86f56f7bbd7&quot;,&quot;output&quot;:{&quot;pinOTP&quot;:&quot;030520&quot;,&quot;pinExpirationDate&quot;:&quot;02/06/2019 07:43 PM GMT&quot;}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "5700" and a string containing "Unfortunately, you have exceeded your attempts for verification. Please try again later.")
     but: a string containing "5700" was "{"transactionId":"0ea540f0-30d8-4bcf-be7c-f86f56f7bbd7","output":{"pinOTP":"030520","pinExpirationDate":"02/06/2019 07:43 PM GMT"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.IssuePinVelocity(MFAC.java:169)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
  <testcase name="IssuePinVelocity" time="2.234" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &quot;pinOTP&quot; and a string containing &quot;pinExpirationDate&quot;)
     but: a string containing &quot;pinOTP&quot; was &quot;{&quot;transactionId&quot;:&quot;2135f7a1-7ed3-4833-94dd-75537fd24922&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "pinOTP" and a string containing "pinExpirationDate")
     but: a string containing "pinOTP" was "{"transactionId":"2135f7a1-7ed3-4833-94dd-75537fd24922","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.IssuePinVelocity(MFAC.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
  <testcase name="IssuePinVelocity" time="2.850" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &quot;pinOTP&quot; and a string containing &quot;pinExpirationDate&quot;)
     but: a string containing &quot;pinOTP&quot; was &quot;{&quot;transactionId&quot;:&quot;9eb1f41c-f8d6-4982-b6d7-4e4f114218fc&quot;,&quot;errors&quot;:[{&quot;code&quot;:&quot;5700&quot;,&quot;message&quot;:&quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;}]}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "pinOTP" and a string containing "pinExpirationDate")
     but: a string containing "pinOTP" was "{"transactionId":"9eb1f41c-f8d6-4982-b6d7-4e4f114218fc","errors":[{"code":"5700","message":"Unfortunately, you have exceeded your attempts for verification. Please try again later."}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.IssuePinVelocity(MFAC.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
  <testcase name="IssuePinVelocity" time="5.700" classname="MFAC.MFAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &quot;5700&quot; and a string containing &quot;Unfortunately, you have exceeded your attempts for verification. Please try again later.&quot;)
     but: a string containing &quot;5700&quot; was &quot;{&quot;transactionId&quot;:&quot;d1f85275-ac02-4e3c-b488-54453c8ba98c&quot;,&quot;output&quot;:{&quot;pinOTP&quot;:&quot;632843&quot;,&quot;pinExpirationDate&quot;:&quot;02/06/2019 07:43 PM GMT&quot;}}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "5700" and a string containing "Unfortunately, you have exceeded your attempts for verification. Please try again later.")
     but: a string containing "5700" was "{"transactionId":"d1f85275-ac02-4e3c-b488-54453c8ba98c","output":{"pinOTP":"632843","pinExpirationDate":"02/06/2019 07:43 PM GMT"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at MFAC.MFAC.IssuePinVelocity(MFAC.java:169)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IssuePinVelocity -->
</testsuite> <!-- MFAC.MFAC -->
