<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WTC-5159473-l2" ignored="1" name="Default test" tests="69" failures="26" timestamp="04 Oct 2018 14:44:18 GMT" time="23.044" errors="0">
  <testcase name="CreateCredentialsForProject" time="0.85" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;output&amp;quot; and a string containing &amp;quot;projectid&amp;quot; and a string containing &amp;quot;creationtime&amp;quot; and a string containing &amp;quot;expirationdate&amp;quot;)
     but: a string containing &amp;quot;output&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;b6212a18-7169-40df-bb83-a26c1850d359&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "output" and a string containing "projectid" and a string containing "creationtime" and a string containing "expirationdate")
     but: a string containing "output" was "{"transactionId":"b6212a18-7169-40df-bb83-a26c1850d359","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateCredentialsForProject(CMAC.java:402)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateCredentialsForProject -->
  <testcase name="CreateCredentialsForProject" time="1.132" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;output&amp;quot; and a string containing &amp;quot;projectid&amp;quot; and a string containing &amp;quot;creationtime&amp;quot; and a string containing &amp;quot;expirationdate&amp;quot;)
     but: a string containing &amp;quot;output&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;d4382556-d8cf-41fa-bd3b-7b6c903ea79e&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "output" and a string containing "projectid" and a string containing "creationtime" and a string containing "expirationdate")
     but: a string containing "output" was "{"transactionId":"d4382556-d8cf-41fa-bd3b-7b6c903ea79e","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateCredentialsForProject(CMAC.java:402)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateCredentialsForProject -->
  <testcase name="CreateCredentialsForProject" time="1.413" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;output&amp;quot; and a string containing &amp;quot;projectid&amp;quot; and a string containing &amp;quot;creationtime&amp;quot; and a string containing &amp;quot;expirationdate&amp;quot;)
     but: a string containing &amp;quot;output&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;9fa78996-92f9-4562-81d1-366ce6f5b6e3&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "output" and a string containing "projectid" and a string containing "creationtime" and a string containing "expirationdate")
     but: a string containing "output" was "{"transactionId":"9fa78996-92f9-4562-81d1-366ce6f5b6e3","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateCredentialsForProject(CMAC.java:402)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateCredentialsForProject -->
  <testcase name="CreateCredentialsForProject" time="1.703" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;output&amp;quot; and a string containing &amp;quot;projectid&amp;quot; and a string containing &amp;quot;creationtime&amp;quot; and a string containing &amp;quot;expirationdate&amp;quot;)
     but: a string containing &amp;quot;output&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;010ff2a0-8346-45fc-9681-d3d271de268c&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "output" and a string containing "projectid" and a string containing "creationtime" and a string containing "expirationdate")
     but: a string containing "output" was "{"transactionId":"010ff2a0-8346-45fc-9681-d3d271de268c","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateCredentialsForProject(CMAC.java:402)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateCredentialsForProject -->
  <testcase name="CreateCredentialsForProject" time="1.994" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;output&amp;quot; and a string containing &amp;quot;projectid&amp;quot; and a string containing &amp;quot;creationtime&amp;quot; and a string containing &amp;quot;expirationdate&amp;quot;)
     but: a string containing &amp;quot;output&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;c34ba8ae-dcb1-403b-bfa8-d2167b089d35&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "output" and a string containing "projectid" and a string containing "creationtime" and a string containing "expirationdate")
     but: a string containing "output" was "{"transactionId":"c34ba8ae-dcb1-403b-bfa8-d2167b089d35","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateCredentialsForProject(CMAC.java:402)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateCredentialsForProject -->
  <testcase name="CreateCredentialsForProject" time="2.299" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;output&amp;quot; and a string containing &amp;quot;projectid&amp;quot; and a string containing &amp;quot;creationtime&amp;quot; and a string containing &amp;quot;expirationdate&amp;quot;)
     but: a string containing &amp;quot;output&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;3de07376-b157-4c9b-873f-24d95ef36b03&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "output" and a string containing "projectid" and a string containing "creationtime" and a string containing "expirationdate")
     but: a string containing "output" was "{"transactionId":"3de07376-b157-4c9b-873f-24d95ef36b03","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateCredentialsForProject(CMAC.java:402)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateCredentialsForProject -->
  <testcase name="CreateCredentialsForProject" time="3.551" classname="TestNG.CMAC"/>
  <testcase name="CreateCredentialsForProject" time="3.822" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;output&amp;quot; and a string containing &amp;quot;projectid&amp;quot; and a string containing &amp;quot;creationtime&amp;quot; and a string containing &amp;quot;expirationdate&amp;quot;)
     but: a string containing &amp;quot;output&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;dea07676-d1ef-483b-9526-474276864f28&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "output" and a string containing "projectid" and a string containing "creationtime" and a string containing "expirationdate")
     but: a string containing "output" was "{"transactionId":"dea07676-d1ef-483b-9526-474276864f28","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateCredentialsForProject(CMAC.java:402)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateCredentialsForProject -->
  <testcase name="CreateProject" time="0.692" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pid&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;244667a9-a8f9-4fe4-a56b-047d503a34e1&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pid"
     but: was "{"transactionId":"244667a9-a8f9-4fe4-a56b-047d503a34e1","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProject(CMAC.java:206)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProject -->
  <testcase name="CreateProject" time="1.284" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pid&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;e69856fb-fee1-4705-8d90-6fb05618fab5&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pid"
     but: was "{"transactionId":"e69856fb-fee1-4705-8d90-6fb05618fab5","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProject(CMAC.java:206)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProject -->
  <testcase name="CreateProject" time="1.898" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pid&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;9c848af7-caf9-42a8-91d2-790f05b4caeb&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pid"
     but: was "{"transactionId":"9c848af7-caf9-42a8-91d2-790f05b4caeb","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProject(CMAC.java:206)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProject -->
  <testcase name="CreateProject" time="2.518" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pid&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;fd09b7f9-9fbe-4787-beab-70de0a70b8bc&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pid"
     but: was "{"transactionId":"fd09b7f9-9fbe-4787-beab-70de0a70b8bc","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProject(CMAC.java:206)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProject -->
  <testcase name="CreateProject" time="3.116" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pid&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;8e5576db-91fb-4b90-82c4-3b7696261db4&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pid"
     but: was "{"transactionId":"8e5576db-91fb-4b90-82c4-3b7696261db4","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProject(CMAC.java:206)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProject -->
  <testcase name="CreateProject" time="3.561" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pid&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;8981c7bc-cf5f-43c9-a667-2a7d4b48b407&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pid"
     but: was "{"transactionId":"8981c7bc-cf5f-43c9-a667-2a7d4b48b407","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProject(CMAC.java:206)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProject -->
  <testcase name="CreateProject" time="4.154" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;pid&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;02ea7344-b1fe-4422-96f0-47370c062b61&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "pid"
     but: was "{"transactionId":"02ea7344-b1fe-4422-96f0-47370c062b61","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProject(CMAC.java:206)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProject -->
  <testcase name="CreateProject" time="5.7" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;cid&amp;quot;
     but: was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;8f3eab3f-6fb8-49f0-9d3d-e169df21c841&amp;quot;,&amp;quot;output&amp;quot;:{&amp;quot;pid&amp;quot;:10371,&amp;quot;projectname&amp;quot;:&amp;quot;Proj_DEL8 100418T094405&amp;quot;,&amp;quot;accountnumber&amp;quot;:&amp;quot;784795640&amp;quot;,&amp;quot;creationtime&amp;quot;:&amp;quot;2018.10.02.15.47.06&amp;quot;,&amp;quot;expirationdate&amp;quot;:&amp;quot;2018.11.02.15.47.06&amp;quot;,&amp;quot;resources&amp;quot;:[&amp;quot;Track Service 0&amp;quot;,&amp;quot;Track Service 1&amp;quot;,&amp;quot;Track Service 2&amp;quot;,&amp;quot;Track Service 3&amp;quot;,&amp;quot;Track Service 4&amp;quot;,&amp;quot;Track Service 5&amp;quot;,&amp;quot;Track Service 6&amp;quot;,&amp;quot;Track Service 7&amp;quot;],&amp;quot;key&amp;quot;:&amp;quot;54IB8WJH9A&amp;quot;}}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "cid"
     but: was "{"transactionId":"8f3eab3f-6fb8-49f0-9d3d-e169df21c841","output":{"pid":10371,"projectname":"Proj_DEL8 100418T094405","accountnumber":"784795640","creationtime":"2018.10.02.15.47.06","expirationdate":"2018.11.02.15.47.06","resources":["Track Service 0","Track Service 1","Track Service 2","Track Service 3","Track Service 4","Track Service 5","Track Service 6","Track Service 7"],"key":"54IB8WJH9A"}}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProject(CMAC.java:206)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProject -->
  <testcase name="CreateProjectInvalidLength" time="0.062" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;code&amp;quot; and a string containing &amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot; and a string containing &amp;quot;message&amp;quot; and a string containing &amp;quot;GENERIC.ERROR&amp;quot;)
     but: a string containing &amp;quot;code&amp;quot; was &amp;quot;{&amp;quot;timestamp&amp;quot;:1538664251564,&amp;quot;status&amp;quot;:400,&amp;quot;error&amp;quot;:&amp;quot;Bad Request&amp;quot;,&amp;quot;exception&amp;quot;:&amp;quot;org.springframework.http.converter.HttpMessageNotReadableException&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;JSON parse error: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token\n at [Source: java.io.PushbackInputStream@7376e882; line: 1, column: 19] (through reference chain: com.fedex.cxs.cmac.v3.vo.ProjectProfileInputVO[\&amp;quot;resourcesInput\&amp;quot;])&amp;quot;,&amp;quot;path&amp;quot;:&amp;quot;/cmac/v3/projects&amp;quot;}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "code" and a string containing "SYSTEM.UNEXPECTED.ERROR" and a string containing "message" and a string containing "GENERIC.ERROR")
     but: a string containing "code" was "{"timestamp":1538664251564,"status":400,"error":"Bad Request","exception":"org.springframework.http.converter.HttpMessageNotReadableException","message":"JSON parse error: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.ArrayList out of VALUE_STRING token\n at [Source: java.io.PushbackInputStream@7376e882; line: 1, column: 19] (through reference chain: com.fedex.cxs.cmac.v3.vo.ProjectProfileInputVO[\"resourcesInput\"])","path":"/cmac/v3/projects"}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProjectInvalidLength(CMAC.java:229)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProjectInvalidLength -->
  <testcase name="DeleteResources" time="0.0" classname="TestNG.CMAC">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: DeleteResources([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) https://cmac-dev.app.wtcdev2.paas.fedex.com/cmac/v3/projects/,(java.lang.String) 10371]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: DeleteResources([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) https://cmac-dev.app.wtcdev2.paas.fedex.com/cmac/v3/projects/,(java.lang.String) 10371]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:954)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- DeleteResources -->
  <testcase name="RetrieveProjectDetails" time="0.062" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.12" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.185" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.247" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.31" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.366" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.417" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.472" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.534" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.592" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.585" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.589" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.587" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.574" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.565" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.571" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.565" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.578" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.57" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.577" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.592" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.592" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.581" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.575" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectDetails" time="0.602" classname="TestNG.CMAC"/>
  <testcase name="UpdateProjectName" time="0.063" classname="TestNG.CMAC">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: UpdateProjectName([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) https://cmac-dev.app.wtcdev2.paas.fedex.com/cmac/v3/projects/,(java.lang.String) 10371,(java.lang.String) Proj Update 100418T094413]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: UpdateProjectName([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) https://cmac-dev.app.wtcdev2.paas.fedex.com/cmac/v3/projects/,(java.lang.String) 10371,(java.lang.String) Proj Update 100418T094413]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:954)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- UpdateProjectName -->
  <testcase name="AddResourcesToProject" time="0.037" classname="TestNG.CMAC"/>
  <testcase name="AddResourcesToProject" time="0.036" classname="TestNG.CMAC"/>
  <testcase name="AddResourcesToProject" time="0.055" classname="TestNG.CMAC"/>
  <testcase name="AddResourcesToProject" time="0.087" classname="TestNG.CMAC"/>
  <testcase name="AddResourcesToProject" time="0.102" classname="TestNG.CMAC"/>
  <testcase name="AddResourcesToProject" time="0.12" classname="TestNG.CMAC"/>
  <testcase name="AddResourcesToProject" time="0.167" classname="TestNG.CMAC"/>
  <testcase name="AddResourcesToProject" time="0.182" classname="TestNG.CMAC"/>
  <testcase name="CreateProjectForTest" time="0.621" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;pid&amp;quot; and a string containing &amp;quot;projectname&amp;quot; and a string containing &amp;quot;cid&amp;quot; and a string containing &amp;quot;accountNumber&amp;quot; and a string containing &amp;quot;creationtime&amp;quot;)
     but: a string containing &amp;quot;pid&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;63827132-9f83-4747-9114-51135ae1c455&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "pid" and a string containing "projectname" and a string containing "cid" and a string containing "accountNumber" and a string containing "creationtime")
     but: a string containing "pid" was "{"transactionId":"63827132-9f83-4747-9114-51135ae1c455","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProjectForTest(CMAC.java:507)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProjectForTest -->
  <testcase name="CreateProjectForTest" time="1.237" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;pid&amp;quot; and a string containing &amp;quot;projectname&amp;quot; and a string containing &amp;quot;cid&amp;quot; and a string containing &amp;quot;accountNumber&amp;quot; and a string containing &amp;quot;creationtime&amp;quot;)
     but: a string containing &amp;quot;pid&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;935d76d2-d37b-4699-a730-4a0b36e250fc&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "pid" and a string containing "projectname" and a string containing "cid" and a string containing "accountNumber" and a string containing "creationtime")
     but: a string containing "pid" was "{"transactionId":"935d76d2-d37b-4699-a730-4a0b36e250fc","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProjectForTest(CMAC.java:507)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProjectForTest -->
  <testcase name="CreateProjectForTest" time="1.836" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;pid&amp;quot; and a string containing &amp;quot;projectname&amp;quot; and a string containing &amp;quot;cid&amp;quot; and a string containing &amp;quot;accountNumber&amp;quot; and a string containing &amp;quot;creationtime&amp;quot;)
     but: a string containing &amp;quot;pid&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;4d912a11-d40b-4b5b-832b-5102683a4038&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "pid" and a string containing "projectname" and a string containing "cid" and a string containing "accountNumber" and a string containing "creationtime")
     but: a string containing "pid" was "{"transactionId":"4d912a11-d40b-4b5b-832b-5102683a4038","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProjectForTest(CMAC.java:507)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProjectForTest -->
  <testcase name="CreateProjectForTest" time="2.398" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;pid&amp;quot; and a string containing &amp;quot;projectname&amp;quot; and a string containing &amp;quot;cid&amp;quot; and a string containing &amp;quot;accountNumber&amp;quot; and a string containing &amp;quot;creationtime&amp;quot;)
     but: a string containing &amp;quot;pid&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;cb1c0e21-66df-49a8-85fd-dc3998b9a82d&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "pid" and a string containing "projectname" and a string containing "cid" and a string containing "accountNumber" and a string containing "creationtime")
     but: a string containing "pid" was "{"transactionId":"cb1c0e21-66df-49a8-85fd-dc3998b9a82d","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProjectForTest(CMAC.java:507)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProjectForTest -->
  <testcase name="CreateProjectForTest" time="2.967" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;pid&amp;quot; and a string containing &amp;quot;projectname&amp;quot; and a string containing &amp;quot;cid&amp;quot; and a string containing &amp;quot;accountNumber&amp;quot; and a string containing &amp;quot;creationtime&amp;quot;)
     but: a string containing &amp;quot;pid&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;d017dcf5-1197-49ff-8bae-1e93404b4ce6&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "pid" and a string containing "projectname" and a string containing "cid" and a string containing "accountNumber" and a string containing "creationtime")
     but: a string containing "pid" was "{"transactionId":"d017dcf5-1197-49ff-8bae-1e93404b4ce6","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProjectForTest(CMAC.java:507)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProjectForTest -->
  <testcase name="CreateProjectForTest" time="3.59" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;pid&amp;quot; and a string containing &amp;quot;projectname&amp;quot; and a string containing &amp;quot;cid&amp;quot; and a string containing &amp;quot;accountNumber&amp;quot; and a string containing &amp;quot;creationtime&amp;quot;)
     but: a string containing &amp;quot;pid&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;331ac2fe-ff87-41e1-b093-59fc22b40333&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "pid" and a string containing "projectname" and a string containing "cid" and a string containing "accountNumber" and a string containing "creationtime")
     but: a string containing "pid" was "{"transactionId":"331ac2fe-ff87-41e1-b093-59fc22b40333","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProjectForTest(CMAC.java:507)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProjectForTest -->
  <testcase name="CreateProjectForTest" time="4.031" classname="TestNG.CMAC">
    <failure type="java.lang.AssertionError" message="
Expected: (a string containing &amp;quot;transactionId&amp;quot; and a string containing &amp;quot;pid&amp;quot; and a string containing &amp;quot;projectname&amp;quot; and a string containing &amp;quot;cid&amp;quot; and a string containing &amp;quot;accountNumber&amp;quot; and a string containing &amp;quot;creationtime&amp;quot;)
     but: a string containing &amp;quot;pid&amp;quot; was &amp;quot;{&amp;quot;transactionId&amp;quot;:&amp;quot;1d9942c6-1900-446b-8551-46dc71fae8de&amp;quot;,&amp;quot;errors&amp;quot;:[{&amp;quot;code&amp;quot;:&amp;quot;SYSTEM.UNEXPECTED.ERROR&amp;quot;,&amp;quot;message&amp;quot;:&amp;quot;GENERIC.ERROR&amp;quot;}]}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: (a string containing "transactionId" and a string containing "pid" and a string containing "projectname" and a string containing "cid" and a string containing "accountNumber" and a string containing "creationtime")
     but: a string containing "pid" was "{"transactionId":"1d9942c6-1900-446b-8551-46dc71fae8de","errors":[{"code":"SYSTEM.UNEXPECTED.ERROR","message":"GENERIC.ERROR"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at TestNG.CMAC.CreateProjectForTest(CMAC.java:507)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- CreateProjectForTest -->
  <testcase name="DeleteCredentials" time="0.016" classname="TestNG.CMAC">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: DeleteCredentials([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) https://cmac-dev.app.wtcdev2.paas.fedex.com/cmac/v3/credentials/,(java.lang.String) 10371]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: DeleteCredentials([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) https://cmac-dev.app.wtcdev2.paas.fedex.com/cmac/v3/credentials/,(java.lang.String) 10371]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:954)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- DeleteCredentials -->
  <testcase name="RetrieveProjectSummary" time="0.073" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectSummary" time="0.136" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectSummary" time="0.183" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectSummary" time="0.246" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectSummary" time="0.303" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectSummary" time="0.35" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectSummary" time="0.426" classname="TestNG.CMAC"/>
  <testcase name="RetrieveProjectSummary" time="0.473" classname="TestNG.CMAC"/>
  <testcase name="DeleteProject" time="0.0" classname="TestNG.CMAC">
    <skipped/>
  </testcase> <!-- DeleteProject -->
  <testcase name="DeleteAllProject" time="0.0" classname="TestNG.CMAC">
    <ignored/>
  </testcase> <!-- DeleteAllProject -->
</testsuite> <!-- Default test -->
