<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3306" started-at="2018-11-14T23:52:43Z" finished-at="2018-11-14T23:52:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3306" started-at="2018-11-14T23:52:43Z" finished-at="2018-11-14T23:52:46Z">
      <class name="USRC.USRC_FDM">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:USRC.USRC_FDM@2698dc7]" name="beforeClass" is-config="true" duration-ms="17" started-at="2018-11-14T23:52:43Z" finished-at="2018-11-14T23:52:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="EndtoEndEnrollment(Data_Structures.USRC_Data, java.lang.String, Data_Structures.MFAC_Data, java.lang.String)[pri:1, instance:USRC.USRC_FDM@2698dc7]" name="EndtoEndEnrollment" duration-ms="1706" started-at="2018-11-14T23:52:44Z" description="380527" data-provider="dp" finished-at="2018-11-14T23:52:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Data_Structures.USRC_Data@5816540c]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[POSTAL]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Data_Structures.MFAC_Data@4b93ed12]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[FDM-POSTCARD-PIN]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"UNEXPECTED_ERROR","message":"The system is unavailable. Please try again later.","contextList":["SENDER"],"source":"WIDM"}]}"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
Expected: a string containing "successful\":true"
     but: was "{"successful":false,"errorList":[{"code":"UNEXPECTED_ERROR","message":"The system is unavailable. Please try again later.","contextList":["SENDER"],"source":"WIDM"}]}"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at USRC.USRC_FDM.EndtoEndEnrollment(USRC_FDM.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndtoEndEnrollment -->
      </class> <!-- USRC.USRC_FDM -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
